import {today,validDate,validWeight,parseWeight,shift,average,normalize,fromCSV,toCSV,DAY} from './data.js';
const $ = s => document.querySelector(s);
const KEY='weight-journal-v1'; let records=[],period='30',storageBroken=false;
const number = n => new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
const dateLabel = d => new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d));
let noticeTimer;
function notice(message,error=false) {clearTimeout(noticeTimer);$('#status').textContent=message;$('#status').classList.toggle('error',error);$('#status').hidden=false;if(!error)noticeTimer=setTimeout(()=>$('#status').hidden=true,5000);}
try {const saved=localStorage.getItem(KEY);if(saved!==null)records=normalize(JSON.parse(saved));} catch { storageBroken=true;notice('Не удалось прочитать хранилище. Данные не перезаписаны. Проверьте настройки браузера и сохранённые данные.',true); }
function save(next) {if(storageBroken){notice('Хранилище недоступно или повреждено. Сохранение заблокировано, чтобы не потерять данные.',true);return false;}try {next=normalize(next);localStorage.setItem(KEY,JSON.stringify(next));records=next;render();return true;}catch {notice('Не удалось сохранить данные. Проверьте доступ к localStorage и свободное место.',true);return false;}}
$('#entry-date').value=today();$('#as-of').value=today();
$('#entry-form').addEventListener('submit',e=>{e.preventDefault();const date=$('#entry-date').value,weight=parseWeight($('#entry-weight').value);if(!validDate(date)||!validWeight(weight)){notice('Введите корректную дату и вес больше 0 и не больше 1000 кг.',true);return;}if(save([...records,{date,weight}])){$('#entry-weight').value='';notice('Запись сохранена.');}});
$('#as-of').addEventListener('change',()=>{if(validDate($('#as-of').value))render();});
document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();}));
function metric(selector,value,signed=false){$(selector).replaceChildren();if(value===null){$(selector).textContent='—';return;}const rounded=Math.round(value*100)/100;$(selector).append(`${signed&&rounded>0?'+':''}${number(rounded)} `);const unit=document.createElement('small');unit.textContent='кг';$(selector).append(unit);}
function render(){const end=validDate($('#as-of').value)?$('#as-of').value:today(),week=average(records,end,7),month=average(records,end,30),prev=average(records,shift(end,-7),7);metric('#average-7',week.value);metric('#average-30',month.value);metric('#trend',week.value!==null&&prev.value!==null?week.value-prev.value:null,true);for(const [days,stat] of [[7,week],[30,month]])$(`#range-${days}`).textContent=`${dateLabel(stat.start)} — ${dateLabel(end)} · записей: ${stat.count}`;$('#trend-detail').textContent=week.value===null||prev.value===null?'Нужны записи в обеих неделях':`К ${dateLabel(prev.start)} — ${dateLabel(prev.end)} · записей: ${prev.count}`;renderChart(end);renderHistory();$('#export').disabled=!records.length;}
function renderHistory(){const host=$('#history');host.replaceChildren();$('#count').textContent=records.length;if(!records.length){host.innerHTML='<div class="empty">Здесь появятся ваши записи.<br>Начните с первого взвешивания.</div>';return;}const table=document.createElement('table');table.innerHTML='<thead><tr><th scope="col">Дата</th><th scope="col">Вес</th><th scope="col">Действия</th></tr></thead>';const body=document.createElement('tbody');for(const r of [...records].reverse()){const tr=document.createElement('tr'),date=document.createElement('td'),weight=document.createElement('td'),actions=document.createElement('td');date.textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(r.date));weight.textContent=`${number(r.weight)} кг`;for(const [title,cls,action] of [['Изменить','',()=>{$('#entry-date').value=r.date;$('#entry-weight').value=String(r.weight);$('#entry-weight').focus();$('#entry-form').scrollIntoView({block:'center',behavior:'auto'});}],['Удалить','delete',()=>{if(confirm(`Удалить запись за ${date.textContent}?`)&&save(records.filter(x=>x.date!==r.date)))notice('Запись удалена.');}]]){const b=document.createElement('button');b.type='button';b.className=`row-action ${cls}`;b.textContent=title;b.setAttribute('aria-label',`${title} запись за ${date.textContent}`);b.onclick=action;actions.append(b);}tr.append(date,weight,actions);body.append(tr);}table.append(body);host.append(table);}
function renderChart(end){const host=$('#chart');host.replaceChildren();const available=records.filter(r=>r.date<=end);const start=period==='all'?(available[0]?.date||shift(end,-29)):shift(end,1-Number(period));const visible=available.filter(r=>r.date>=start);if(!visible.length){host.innerHTML='<div class="empty">Нет записей за этот период.<br>Добавьте вес или выберите другой период.</div>';return;}
  // Only dates whose seven-day windows contain a measurement need points.
  const dates=new Set();for(const r of available.filter(r=>r.date>=shift(start,-6)))for(let i=0;i<7;i++){const d=shift(r.date,i);if(d>=start&&d<=end)dates.add(d);}
  const means=[...dates].sort().map(date=>({date,weight:average(available,date,7).value}));
  const values=[...visible,...means].map(r=>r.weight);let low=Math.min(...values),high=Math.max(...values);const pad=Math.max((high-low)*.2,.5);low-=pad;high+=pad;
  const W=860,H=290,L=55,R=18,T=18,B=40,span=Math.max(DAY,Date.parse(end)-Date.parse(start));const x=d=>L+(Date.parse(d)-Date.parse(start))/span*(W-L-R);const y=w=>T+(high-w)/(high-low)*(H-T-B);
  const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.classList.add('chart');svg.setAttribute('role','img');svg.setAttribute('aria-label',`График веса: ${dateLabel(start)} — ${dateLabel(end)}. Точные значения доступны в таблице записей.`);
  const add=(tag,attrs,text)=>{const el=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;svg.append(el);return el;};
  for(let i=0;i<5;i++){const value=low+(high-low)*i/4,cy=y(value);add('line',{x1:L,y1:cy,x2:W-R,y2:cy,stroke:'#edf0e9'});add('text',{x:L-10,y:cy+4,'text-anchor':'end',fill:'#819085','font-size':11},number(value));}
  for(let i=0;i<4;i++){const d=shift(start,Math.round((Date.parse(end)-Date.parse(start))/DAY*i/3));if(i&&d===start)continue;add('text',{x:x(d),y:H-10,'text-anchor':i===0?'start':i===3?'end':'middle',fill:'#819085','font-size':11},dateLabel(d));}
  add('polyline',{points:visible.map(r=>`${x(r.date)},${y(r.weight)}`).join(' '),fill:'none',stroke:'#315e4c','stroke-width':2.5,'stroke-linejoin':'round'});
  let path='';means.forEach((r,i)=>{const gap=!i||Date.parse(r.date)-Date.parse(means[i-1].date)>DAY;path+=`${gap?'M':'L'}${x(r.date)} ${y(r.weight)} `;});add('path',{d:path,fill:'none',stroke:'#a5b875','stroke-width':2.5,'stroke-dasharray':'5 5'});
  for(const r of visible){const dot=add('circle',{cx:x(r.date),cy:y(r.weight),r:4,fill:'#315e4c',stroke:'#fff','stroke-width':2});const title=document.createElementNS(ns,'title');title.textContent=`${r.date}: ${number(r.weight)} кг`;dot.append(title);}host.append(svg);
}
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([toCSV(records)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`weight-journal-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onclick=()=>$('#csv-file').click();
$('#csv-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('Максимальный размер CSV — 2 МБ.');const imported=fromCSV(await file.text());const overlaps=imported.filter(r=>records.some(x=>x.date===r.date)).length;if(overlaps&&!confirm(`Импорт обновит записи за ${overlaps} дат. Продолжить?`))return;if(save([...records,...imported]))notice(`Импортировано записей: ${imported.length}.`);}catch(error){notice(error.message,true);}finally{e.target.value='';}};
window.addEventListener('storage',e=>{if(e.key===KEY||e.key===null){try{records=normalize(JSON.parse(localStorage.getItem(KEY)||'[]'));storageBroken=false;render();}catch{storageBroken=true;notice('Данные изменились в другой вкладке, но не удалось их прочитать.',true);}}});
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notice('Офлайн-режим недоступен. Откройте приложение по HTTPS или через localhost.',true));
